ci: use lerna

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -65,33 +65,36 @@ jobs:
           tag="pr-${{ github.event.pull_request.number }}"
           echo "preid=${preid}"
 
-          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
+          git checkout ${{ github.head_ref }}
 
-          pnpm version --prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --no-git-tag-version --yes --amend
+          pnpm --silent lerna version prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --conventional-prerelease --yes --amend || true
 
-          package_version=$(jq -r ".version" package.json)
-          package=@kong/markdown@"${package_version}"
+          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
 
-          npm show "${package}" >/dev/null 2>&1 && npm_show_status=0 || npm_show_status=1
-          if [ $npm_show_status -eq 0 ]; then
-            echo "Package ${package} is already published. Skipping publishing."
+          pnpmPublish=$(pnpm publish --no-git-checks --access public --report-summary --tag "${tag}")
+
+          if [[ ! -z $(echo "${pnpmPublish}"|grep "There are no new packages that should be published") ]]; then
+            echo "There are no new packages that should be published"
             exit 0
           fi
 
           npm_instructions=""
+          pkg=$(echo "${pnpmPublish}" | grep "+ "| sed 's/+ //')
 
-          pkg=$(npm publish --no-git-checks --access public --report-summary --tag "${tag}" | grep "+ "| sed 's/+ //')
+          pkg="@$(echo ${pkg}|cut -d'@' -f2)@${tag}"
+          if [ "${npm_instructions}" != "" ]; then
+            npm_instructions="${npm_instructions}\n"
+          fi
+          npm_instructions="${npm_instructions}${pkg}"
 
-          if [[ -z "${pkg}" ]]; then
-            echo "Error publishing package"
+          if [[ -z "${npm_instructions}" ]]; then
+            echo "Error creating preview instructions"
             exit -1
           fi
 
-          npm_instructions="pnpm add @$(echo ${pkg}|cut -d'@' -f2)@${tag}"
-
-          echo "npm_instructions<<EOF" >> $GITHUB_OUTPUT
-          echo -e "$npm_instructions" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
+          echo "npm_instructions<<EOF" >> $GITHUB_ENV
+          echo -e "$npm_instructions" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
 
       - name: Provide preview link info
         if: ${{ steps.package-preview.outputs.npm_instructions != '' }}
