feat: tooltips and buttons

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -9,6 +9,8 @@ on:
       - labeled
     branches:
       - main
+      - alpha
+      - beta
 
   # Allow calling manually from GitHub
   workflow_dispatch:
@@ -52,57 +54,57 @@ jobs:
       - name: Test
         run: pnpm run test
 
-      # - name: Publish package preview
-      #   id: package-preview
-      #   # Do not run for `alpha` or `beta` branches
-      #   if: github.event_name == 'pull_request' && (github.actor != 'renovate[bot]' || contains(github.event.pull_request.labels.*.name, 'create preview package'))
-      #   env:
-      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLIC_PUBLISH }}
-      #   run: |
-      #     git config user.email "konnectx-engineers+kongponents-bot@konghq.com"
-      #     git config user.name "Kong UI Bot"
+      - name: Publish package preview
+        id: package-preview
+        # Do not run for `alpha` or `beta` branches
+        if: github.event_name == 'pull_request' && (github.actor != 'renovate[bot]' || contains(github.event.pull_request.labels.*.name, 'create preview package'))
+        env:
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLIC_PUBLISH }}
+        run: |
+          git config user.email "konnectx-engineers+kongponents-bot@konghq.com"
+          git config user.name "Kong UI Bot"
 
-      #     preid="pr.${{ github.event.pull_request.number }}.$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"
-      #     tag="pr-${{ github.event.pull_request.number }}"
-      #     echo "preid=${preid}"
+          preid="pr.${{ github.event.pull_request.number }}.$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"
+          tag="pr-${{ github.event.pull_request.number }}"
+          echo "preid=${preid}"
 
-      #     echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
+          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
 
-      #     pnpm --silent lerna version prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --conventional-prerelease --yes --amend || true
+          pnpm --silent lerna version prerelease --preid ${preid} --allow-branch ${{ github.head_ref }} --conventional-prerelease --yes --amend || true
 
-      #     package_version=$(jq -r ".version" package.json)
-      #     package=@kong/markdown@"${package_version}"
+          package_version=$(jq -r ".version" package.json)
+          package=@kong/markdown@"${package_version}"
 
-      #     npm show "${package}" >/dev/null 2>&1 && npm_show_status=0 || npm_show_status=1
-      #     if [ $npm_show_status -eq 0 ]; then
-      #       echo "Package ${package} is already published. Skipping publishing."
-      #       exit 0
-      #     fi
+          npm show "${package}" >/dev/null 2>&1 && npm_show_status=0 || npm_show_status=1
+          if [ $npm_show_status -eq 0 ]; then
+            echo "Package ${package} is already published. Skipping publishing."
+            exit 0
+          fi
 
-      #     npm_instructions=""
+          npm_instructions=""
 
-      #     pkg=$(npm publish --no-git-checks --access public --report-summary --tag "${tag}" | grep "+ "| sed 's/+ //')
+          pkg=$(npm publish --no-git-checks --access public --report-summary --tag "${tag}" | grep "+ "| sed 's/+ //')
 
-      #     if [[ -z "${pkg}" ]]; then
-      #       echo "Error publishing package"
-      #       exit -1
-      #     fi
+          if [[ -z "${pkg}" ]]; then
+            echo "Error publishing package"
+            exit -1
+          fi
 
-      #     npm_instructions="pnpm add @$(echo ${pkg}|cut -d'@' -f2)@${tag}"
+          npm_instructions="pnpm add @$(echo ${pkg}|cut -d'@' -f2)@${tag}"
 
-      #     echo "npm_instructions<<EOF" >> $GITHUB_OUTPUT
-      #     echo -e "$npm_instructions" >> $GITHUB_OUTPUT
-      #     echo "EOF" >> $GITHUB_OUTPUT
+          echo "npm_instructions<<EOF" >> $GITHUB_OUTPUT
+          echo -e "$npm_instructions" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
 
-      # - name: Provide preview link info
-      #   if: ${{ steps.package-preview.outputs.npm_instructions != '' }}
-      #   uses: marocchino/sticky-pull-request-comment@v2
-      #   with:
-      #     header: pr_preview_consumption
-      #     message: |
-      #        ### Install the preview package from this PR
+      - name: Provide preview link info
+        if: ${{ steps.package-preview.outputs.npm_instructions != '' }}
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          header: pr_preview_consumption
+          message: |
+             ### Install the preview package from this PR
 
-      #        ```sh
-      #        ${{ steps.package-preview.outputs.npm_instructions }}
-      #        ```
-      #     GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
+             ```sh
+             ${{ steps.package-preview.outputs.npm_instructions }}
+             ```
+          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
